- name: install nodejs
  hosts: frontend
  become: yes
  tasks:

  - name: install nginbx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes