- name: install multi plays
  hosts: vishu
  become: yes
  tasks:

  - name: install nodejs
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes


- name: install nodejs
  hosts: local
  become: yes
  connection: local
  tasks:

  - name: install nodejs
    ansible.builtin.package:
      name: nginx
      state: present

